## Average Accuracy Calculation

In [2]:
import os
import json
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score
import numpy as np
import pandas as pd

def read_json(path):
    with open(path, 'r', encoding="utf-8") as f:
        data = json.load(f)
    return data

def write_json(data, path):
    if not os.path.exists(os.path.dirname(path)):
        os.makedirs(os.path.dirname(path))
    with open(path, 'w', encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

In [34]:
# results-
experiments = {'run_1':'/Users/sefika/phd_projects/llm-catastrophic-re/results-finance/finance/results/llm_forget_mas/model_1_forgetting_matrix.json',
               'run_2': '/Users/sefika/phd_projects/llm-catastrophic-re/results-finance/finance/results/llm_forget_mas/model_2_forgetting_matrix.json' ,
               'run_3': '/Users/sefika/phd_projects/llm-catastrophic-re/results-finance/finance/results/llm_forget_mas/model_3_forgetting_matrix.json',
               'run_4': '/Users/sefika/phd_projects/llm-catastrophic-re/results-finance/finance/results/llm_forget_mas/model_4_forgetting_matrix.json',
               'run_5': '/Users/sefika/phd_projects/llm-catastrophic-re/results-finance/finance/results/llm_forget_mas/model_5_forgetting_matrix.json'}

In [35]:
data1 = read_json(experiments['run_1'])
data2 = read_json(experiments['run_2'])
data3 = read_json(experiments['run_3'])
data4 = read_json(experiments['run_4'])
data5 = read_json(experiments['run_5'])

In [36]:
data1 = pd.DataFrame(data1)
data2 = pd.DataFrame(data2)
data3 = pd.DataFrame(data3)
data4 = pd.DataFrame(data4)
data5 = pd.DataFrame(data5)

In [37]:
combined = pd.concat([data1, data2, data3, data4, data5])

In [38]:
results = []
for base in range(1,6):
    total_task_accuracy =[]
    std = 0
    for task in range(1,base+1):
        acc = combined[(combined['base_task'] == base) & (combined['task'] == task)]['accuracy'].values

        if acc.size > 0:
            total_task_accuracy.append(sum(acc) / len(acc))
        if base == 1 and task == 1:
            std = np.std(acc) if len(acc) > 0 else 0
    if base == 1:
        row = {
            "base": base,
            "mean_accuracy": (sum(total_task_accuracy) / len(total_task_accuracy))*100 if total_task_accuracy else 0,
            "standard_deviation": std*100 if total_task_accuracy else 0
        }
        results.append(row)
    else:
        row = {
            "base": base,
            "mean_accuracy": (sum(total_task_accuracy) / len(total_task_accuracy))*100 if total_task_accuracy else 0,
            "standard_deviation": (np.std(total_task_accuracy))*100 if total_task_accuracy else 0
        }
    results.append(row)

In [39]:
# mas results
results_df = pd.DataFrame(results)
results_df.T

,0,1,2,3,4,5
base,1.000000,1.000000,2.000000,3.000000,4.000000,5.000000
mean_accuracy,97.003058,97.003058,96.761743,95.992956,93.096818,85.223430
standard_deviation,1.259404,1.259404,0.363639,0.819427,3.102557,12.760716

In [40]:
results_df.to_csv('/Users/sefika/phd_projects/llm-catastrophic-re/results-finance/finance/results/llm_forget_mas/icl_finance_acc.csv', index=False)

In [31]:
# si results
results_df = pd.DataFrame(results)
results_df.T

,0,1,2,3,4,5
base,1.000000,1.000000,2.000000,3.000000,4.000000,5.000000
mean_accuracy,97.492355,97.492355,97.243358,96.325241,93.360628,84.529063
standard_deviation,0.122324,0.122324,0.371320,0.958795,2.837970,13.985302

In [33]:
results_df.to_csv('/Users/sefika/phd_projects/llm-catastrophic-re/results-finance/finance/results/si_finance_flan_random/icl_finance_acc.csv', index=False)

In [17]:
#ewc results

results_df = pd.DataFrame(results)
results_df.T

,0,1,2,3,4,5
base,1.000000,1.000000,2.000000,3.000000,4.000000,5.000000
mean_accuracy,97.675841,97.675841,97.101178,96.037913,93.288830,84.704474
standard_deviation,0.244648,0.244648,0.513501,1.014904,3.518502,13.434006

In [19]:
results_df.to_csv('/Users/sefika/phd_projects/llm-catastrophic-re/results-finance/finance/results/llm_forget_ewc/icl_finance_acc.csv', index=False)

In [ ]:
#base results

results_df = pd.DataFrame(results)
results_df.T

,0,1,2,3,4,5
base,1.000000,1.000000,2.000000,3.000000,4.000000,5.000000
mean_accuracy,97.737003,97.737003,96.850443,96.145524,93.609705,85.166429
standard_deviation,0.366972,0.366972,0.641912,1.040531,2.797607,13.920028

In [ ]:
results_df.to_csv('/Users/sefika/phd_projects/llm-catastrophic-re/results-finance/finance/results/llm_forget_baseline/icl_finance_acc.csv', index=False)