## Average Accuracy Calculation

In [13]:
import os
import json
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score
import numpy as np
import pandas as pd

def read_json(path):
    with open(path, 'r', encoding="utf-8") as f:
        data = json.load(f)
    return data

def write_json(data, path):
    if not os.path.exists(os.path.dirname(path)):
        os.makedirs(os.path.dirname(path))
    with open(path, 'w', encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

In [14]:

base_experiments = {'run_1':'/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/base/model_1_forgetting_matrix.json',
               'run_2': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/base/model_2_forgetting_matrix.json' ,
               'run_3': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/base/model_3_forgetting_matrix.json',
               'run_4': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/base/model_4_forgetting_matrix.json',
               'run_5': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/base/model_5_forgetting_matrix.json'}

In [15]:
ewc_experiments = {'run_1':'/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/ewc/model_1_forgetting_matrix.json',
               'run_2': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/ewc/model_2_forgetting_matrix.json' ,
               'run_3': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/ewc/model_3_forgetting_matrix.json',
               'run_4': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/ewc/model_4_forgetting_matrix.json',
               'run_5': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/ewc/model_5_forgetting_matrix.json'}

In [16]:
si_experiments = {'run_1':'/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/si/model_1_forgetting_matrix.json',
               'run_2': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/si/model_2_forgetting_matrix.json' ,
               'run_3': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/si/model_3_forgetting_matrix.json',
                'run_4': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/si/model_4_forgetting_matrix.json',
                'run_5': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/si/model_5_forgetting_matrix.json'
                }

In [17]:
mas_experiments = {'run_1':'/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/mas/model_1_forgetting_matrix.json',
                'run_2': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/mas/model_2_forgetting_matrix.json' ,
                'run_3': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/mas/model_3_forgetting_matrix.json',
                'run_4': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/mas/model_4_forgetting_matrix.json',
                'run_5': '/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/mas/model_5_forgetting_matrix.json'
                }

In [21]:
def results_mean_acc_std(combined):
    results = []
    for base in range(1,6):
        total_task_accuracy =[]
        std = 0
        for task in range(1,base+1):
            acc = combined[(combined['base_task'] == base) & (combined['task'] == task)]['accuracy'].values
            print(f"Base: {base}, Task: {task}, Accuracies: {acc}")
            if acc.size > 0:
                total_task_accuracy.append(sum(acc) / len(acc))
            if base == 1 and task == 1:
                std = np.std(acc) if len(acc) > 0 else 0
        if base == 1:
            row = {
                "base": base,
                "mean_accuracy": (sum(total_task_accuracy) / len(total_task_accuracy))*100 if total_task_accuracy else 0,
                "standard_deviation": std*100 if total_task_accuracy else 0
            }
            results.append(row)
        else:
            row = {
                "base": base,
                "mean_accuracy": (sum(total_task_accuracy) / len(total_task_accuracy))*100 if total_task_accuracy else 0,
                "standard_deviation": (np.std(total_task_accuracy))*100 if total_task_accuracy else 0
            }
        results.append(row)
    return results

In [23]:
# base_data1 = read_json(base_experiments['run_1'])
base_data2 = read_json(base_experiments['run_2'])
base_data3 = read_json(base_experiments['run_3'])
base_data4 = read_json(base_experiments['run_4'])
base_data5 = read_json(base_experiments['run_5'])
# base_data1 = pd.DataFrame(base_data1)
base_data2 = pd.DataFrame(base_data2)
base_data3 = pd.DataFrame(base_data3)
base_data4 = pd.DataFrame(base_data4)
base_data5 = pd.DataFrame(base_data5)
base_combined = pd.concat([ base_data2, base_data3, base_data4, base_data5])
results = results_mean_acc_std(base_combined)
results_df = pd.DataFrame(results)
results_df.to_json('/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/base/mean_std_icl_acc.json', orient='records', indent=4)
results_df.T

Base: 1, Task: 1, Accuracies: [0.82463466 0.71411625 0.79356568 0.40620272]
Base: 2, Task: 1, Accuracies: [0.782881   0.64531435 0.88382484 0.51815431]
Base: 2, Task: 2, Accuracies: [1.         1.         0.97058824 1.        ]
Base: 3, Task: 1, Accuracies: [0.81419624 0.79003559 0.94191242 0.7526475 ]
Base: 3, Task: 2, Accuracies: [1.         1.         0.97058824 1.        ]
Base: 3, Task: 3, Accuracies: [0.86046512 1.         0.95238095 1.        ]
Base: 4, Task: 1, Accuracies: [0.82254697 0.76156584 0.92672029 0.77004539]
Base: 4, Task: 2, Accuracies: [1.         1.         0.94117647 1.        ]
Base: 4, Task: 3, Accuracies: [0.88372093 1.         0.95238095 1.        ]
Base: 4, Task: 4, Accuracies: [1. 1. 1. 1.]
Base: 5, Task: 1, Accuracies: [0.92066806 0.80427046 0.94101877 0.82980333]
Base: 5, Task: 2, Accuracies: [1.         1.         0.94117647 1.        ]
Base: 5, Task: 3, Accuracies: [0.8372093 1.        0.9047619 1.       ]
Base: 5, Task: 4, Accuracies: [1.  0.8 1.  1. ]
Base: 5, Task: 5, Accuracies: [1.   1.   1.   0.75]

,0,1,2,3,4,5
base,1.000000,1.000000,2.000000,3.000000,4.000000,5.000000
mean_accuracy,68.462983,68.462983,85.009534,92.351884,94.113480,93.644541
standard_deviation,16.572528,16.572528,14.255172,7.170759,7.133673,3.599680

In [20]:

results

[{'base': 1,
  'mean_accuracy': 72.77038627616037,
  'standard_deviation': 17.144498995221632},
 {'base': 1,
  'mean_accuracy': 72.77038627616037,
  'standard_deviation': 17.144498995221632},
 {'base': 2,
  'mean_accuracy': 83.97588142965986,
  'standard_deviation': 10.991438831778034},
 {'base': 3,
  'mean_accuracy': 90.50584568368045,
  'standard_deviation': 6.943277181192296},
 {'base': 4, 'mean_accuracy': nan, 'standard_deviation': nan},
 {'base': 5, 'mean_accuracy': nan, 'standard_deviation': nan}]

In [24]:
# si_data1 = read_json(si_experiments['run_1'])
si_data2 = read_json(si_experiments['run_2'])
si_data3 = read_json(si_experiments['run_3'])
si_data4 = read_json(si_experiments['run_4'])
si_data5 = read_json(si_experiments['run_5'])
# si_data1 = pd.DataFrame(si_data1)
si_data2 = pd.DataFrame(si_data2)
si_data3 = pd.DataFrame(si_data3)
si_data4 = pd.DataFrame(si_data4)
si_data5 = pd.DataFrame(si_data5)
si_combined = pd.concat([si_data2, si_data3, si_data4, si_data5])
results = results_mean_acc_std(si_combined)
results_df = pd.DataFrame(results)
results_df.to_json('/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/si/mean_std_icl_acc.json', orient='records', indent=4)
results_df.T

Base: 1, Task: 1, Accuracies: [0.82881002 0.71055753 0.79088472 0.40847201]
Base: 2, Task: 1, Accuracies: [0.78496868 0.64650059 0.88114388 0.51437216]
Base: 2, Task: 2, Accuracies: [1.         1.         0.97058824 1.        ]
Base: 3, Task: 1, Accuracies: [0.81628392 0.78410439 0.94280608 0.75189107]
Base: 3, Task: 2, Accuracies: [1.         1.         0.97058824 1.        ]
Base: 3, Task: 3, Accuracies: [0.86046512 1.         0.95238095 1.        ]
Base: 4, Task: 1, Accuracies: [0.82045929 0.76512456 0.92582663 0.76928896]
Base: 4, Task: 2, Accuracies: [1.         1.         0.94117647 1.        ]
Base: 4, Task: 3, Accuracies: [0.86046512 1.         0.95238095 1.        ]
Base: 4, Task: 4, Accuracies: [1. 1. 1. 1.]
Base: 5, Task: 1, Accuracies: [0.91858038 0.80427046 0.94369973 0.82980333]
Base: 5, Task: 2, Accuracies: [1.         1.         0.94117647 1.        ]
Base: 5, Task: 3, Accuracies: [0.81395349 1.         0.9047619  1.        ]
Base: 5, Task: 4, Accuracies: [1.  0.8 1.  1. ]
Base: 5, Task: 5, Accuracies: [1.   1.   1.   0.75]

,0,1,2,3,4,5
base,1.000000,1.000000,2.000000,3.000000,4.000000,5.000000
mean_accuracy,68.468107,68.468107,84.969669,92.320998,93.967012,93.531229
standard_deviation,16.508589,16.508589,14.295036,7.213330,7.103473,3.605215

In [25]:
# ewc_data1 = read_json(ewc_experiments['run_1'])
ewc_data2 = read_json(ewc_experiments['run_2'])
ewc_data3 = read_json(ewc_experiments['run_3'])
ewc_data4 = read_json(ewc_experiments['run_4'])
ewc_data5 = read_json(ewc_experiments['run_5'])
# ewc_data1 = pd.DataFrame(ewc_data1)
ewc_data2 = pd.DataFrame(ewc_data2)
ewc_data3 = pd.DataFrame(ewc_data3)
ewc_data4 = pd.DataFrame(ewc_data4)
ewc_data5 = pd.DataFrame(ewc_data5)
ewc_combined = pd.concat([ewc_data2, ewc_data3, ewc_data4, ewc_data5])
results = results_mean_acc_std(ewc_combined)
results_df = pd.DataFrame(results)
results_df.to_json('/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/ewc/mean_std_icl_acc.json', orient='records', indent=4)
results_df.T

Base: 1, Task: 1, Accuracies: [0.82254697 0.68683274 0.78552279 0.48865356]
Base: 2, Task: 1, Accuracies: [0.7348643  0.63107948 0.89186774 0.52496218]
Base: 2, Task: 2, Accuracies: [1.         1.         0.97058824 1.        ]
Base: 3, Task: 1, Accuracies: [0.71189979 0.89561091 0.91599643 0.76853253]
Base: 3, Task: 2, Accuracies: [1.         1.         0.97058824 1.        ]
Base: 3, Task: 3, Accuracies: [0.74418605 1.         0.97619048 1.        ]
Base: 4, Task: 1, Accuracies: [0.7223382  0.88137604 0.91242181 0.7526475 ]
Base: 4, Task: 2, Accuracies: [1.         1.         0.97058824 1.        ]
Base: 4, Task: 3, Accuracies: [0.79069767 1.         0.95238095 1.        ]
Base: 4, Task: 4, Accuracies: [1.         0.86666667 1.         1.        ]
Base: 5, Task: 1, Accuracies: [0.91231733 0.88849348 0.93208222 0.8290469 ]
Base: 5, Task: 2, Accuracies: [1.         1.         0.91176471 1.        ]
Base: 5, Task: 3, Accuracies: [0.69767442 1.         0.97619048 1.        ]
Base: 5, Task: 4, Accuracies: [1.         0.86666667 1.         1.        ]
Base: 5, Task: 5, Accuracies: [1.   1.   1.   0.75]

,0,1,2,3,4,5
base,1.000000,1.000000,2.000000,3.000000,4.000000,5.000000
mean_accuracy,69.588901,69.588901,84.417024,91.525037,92.806982,93.821181
standard_deviation,12.952317,12.952317,14.847682,7.004495,6.710487,3.180046

In [26]:
# mas_data1 = read_json(mas_experiments['run_1'])
mas_data2 = read_json(mas_experiments['run_2'])
mas_data3 = read_json(mas_experiments['run_3'])
mas_data4 = read_json(mas_experiments['run_4'])
mas_data5 = read_json(mas_experiments['run_5'])
# mas_data1 = pd.DataFrame(mas_data1)
mas_data2 = pd.DataFrame(mas_data2)
mas_data3 = pd.DataFrame(mas_data3)
mas_data4 = pd.DataFrame(mas_data4)
mas_data5 = pd.DataFrame(mas_data5)
mas_combined = pd.concat([mas_data2, mas_data3, mas_data4, mas_data5])
results = results_mean_acc_std(mas_combined)
results_df = pd.DataFrame(results)
results_df.to_json('/Users/sefika/phd_projects/llm-catastrophic-re/results_all/last_results/corona/mas/mean_std_icl_acc.json', orient='records', indent=4)
results_df.T

Base: 1, Task: 1, Accuracies: [0.82672234 0.742586   0.76764969 0.47503782]
Base: 2, Task: 1, Accuracies: [0.80793319 0.69869514 0.77211796 0.59909228]
Base: 2, Task: 2, Accuracies: [1.         0.91666667 0.97058824 1.        ]
Base: 3, Task: 1, Accuracies: [0.68058455 0.88493476 0.86237712 0.83282905]
Base: 3, Task: 2, Accuracies: [1.         1.         0.97058824 1.        ]
Base: 3, Task: 3, Accuracies: [0.8372093  1.         0.95238095 1.        ]
Base: 4, Task: 1, Accuracies: [0.71189979 0.81494662 0.88918677 0.82299546]
Base: 4, Task: 2, Accuracies: [1.         1.         0.94117647 1.        ]
Base: 4, Task: 3, Accuracies: [0.69767442 0.92592593 0.95238095 1.        ]
Base: 4, Task: 4, Accuracies: [1. 1. 1. 1.]
Base: 5, Task: 1, Accuracies: [0.9394572  0.79359431 0.91599643 0.87291982]
Base: 5, Task: 2, Accuracies: [1. 1. 1. 1.]
Base: 5, Task: 3, Accuracies: [0.62790698 0.96296296 0.95238095 1.        ]
Base: 5, Task: 4, Accuracies: [1. 1. 1. 1.]
Base: 5, Task: 5, Accuracies: [1.         1.         1.         0.69642857]

,0,1,2,3,4,5
base,1.000000,1.000000,2.000000,3.000000,4.000000,5.000000
mean_accuracy,70.299896,70.299896,84.563668,91.840866,92.226165,93.808236
standard_deviation,13.511163,13.511163,12.617704,7.529402,7.660383,5.274783