In [1]:
import pandas as pd
import json

In [2]:
fewrel_bertscore_paths = {
    'mas': "/Users/sefika/phd_projects/llm-catastrophic-re/fewrel_corrected_results/tmlr/mas/bertscore_results.json",
    'ewc': "/Users/sefika/phd_projects/llm-catastrophic-re/fewrel_corrected_results/tmlr/ewc/bertscore_results.json",
    'si': "/Users/sefika/phd_projects/llm-catastrophic-re/fewrel_corrected_results/tmlr/si/bertscore_results.json",
    'baseline': "/Users/sefika/phd_projects/llm-catastrophic-re/fewrel_corrected_results/tmlr/baseline/bertscore_results.json"
}

In [23]:
tacred_bertscore_paths = {
    'mas': "/Users/sefika/phd_projects/llm-catastrophic-re/last_results/tacred/probs/tacred_mas_top_prob_5/bertscore_results.json",
    'ewc': "/Users/sefika/phd_projects/llm-catastrophic-re/last_results/tacred/probs/tacred_ewc_top_prob_5/bertscore_results.json",
    'si': "/Users/sefika/phd_projects/llm-catastrophic-re/last_results/tacred/probs/tacred_si_top_prob_5/bertscore_results.json",
    'baseline': "/Users/sefika/phd_projects/llm-catastrophic-re/last_results/tacred/baseline/bertscore_results.json"
}

In [4]:
fewrel_mas_df = pd.read_json(fewrel_bertscore_paths['mas'])
fewrel_ewc_df = pd.read_json(fewrel_bertscore_paths['ewc'])
fewrel_si_df = pd.read_json(fewrel_bertscore_paths['si'])
fewrel_baseline_df = pd.read_json(fewrel_bertscore_paths['baseline'])

In [14]:
# f1, precision, recall columns for fewrel
# fewrel_metrics = ['f1', 'precision', 'recall']
fewrel_mas_mean = fewrel_mas_df.groupby('task_id').mean()
# fewrel_mas_mean.T



fewrel_ewc_mean = fewrel_ewc_df.groupby('task_id').mean()



fewrel_si_mean = fewrel_si_df.groupby('task_id').mean()


fewrel_baseline_mean = fewrel_baseline_df.groupby('task_id').mean()

In [15]:
fewrel_mas_mean.T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
avg_precision,0.990055,0.954231,0.935923,0.934454,0.928884,0.929216,0.928593,0.928789
avg_recall,0.989943,0.953505,0.932629,0.932992,0.926970,0.925350,0.926644,0.926708
avg_f1,0.989728,0.952972,0.932818,0.932522,0.926544,0.925652,0.926225,0.926236

In [16]:
fewrel_si_mean.T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
avg_precision,0.988687,0.955389,0.939949,0.936900,0.931816,0.933846,0.933541,0.930218
avg_recall,0.987734,0.955715,0.937268,0.934954,0.928652,0.931992,0.931826,0.928714
avg_f1,0.987894,0.954651,0.937320,0.934673,0.928854,0.931574,0.931442,0.928059

In [17]:
fewrel_baseline_mean.T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
avg_precision,0.988781,0.954254,0.937286,0.934890,0.930354,0.933709,0.934366,0.930596
avg_recall,0.987825,0.954485,0.934725,0.932829,0.927226,0.931690,0.932555,0.929069
avg_f1,0.987987,0.953458,0.934657,0.932560,0.927429,0.931348,0.932219,0.928402

In [18]:
fewrel_ewc_mean.T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
avg_precision,0.990220,0.952454,0.935495,0.933913,0.929235,0.930259,0.928716,0.929029
avg_recall,0.990065,0.952079,0.932681,0.932495,0.927759,0.927535,0.927021,0.927329
avg_f1,0.989876,0.951340,0.932637,0.932023,0.927202,0.927486,0.926523,0.926762

## TACRED

In [19]:
tacred_si_df = pd.read_json(tacred_bertscore_paths['si'])
tacred_si_mean = tacred_si_df.groupby('task_id').mean()
tacred_si_mean.T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
avg_precision,0.960570,0.964145,0.962857,0.961829,0.956563,0.945274,0.944582,0.946264
avg_recall,0.963411,0.969854,0.967589,0.968111,0.964729,0.954304,0.952802,0.955956
avg_f1,0.961813,0.966658,0.964765,0.964404,0.960003,0.948989,0.947912,0.950265

In [20]:
tacred_mas_df = pd.read_json(tacred_bertscore_paths['mas'])
tacred_mas_mean = tacred_mas_df.groupby('task_id').mean()
tacred_mas_mean.T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
avg_precision,0.959727,0.962665,0.962318,0.963031,0.960655,0.951918,0.948454,0.950128
avg_recall,0.962225,0.968396,0.966506,0.966986,0.965172,0.957343,0.955092,0.958477
avg_f1,0.960800,0.965147,0.963964,0.964494,0.962334,0.953922,0.951011,0.953549

In [21]:
tacred_ewc_df = pd.read_json(tacred_bertscore_paths['ewc'])
tacred_ewc_mean = tacred_ewc_df.groupby('task_id').mean()
tacred_ewc_mean.T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
avg_precision,0.959818,0.962064,0.961689,0.962841,0.961255,0.951083,0.948672,0.950174
avg_recall,0.962337,0.967993,0.965975,0.966740,0.965773,0.956583,0.955519,0.958491
avg_f1,0.960904,0.964634,0.963380,0.964263,0.962951,0.953123,0.951334,0.953565

In [24]:
tacred_baseline_df = pd.read_json(tacred_bertscore_paths['baseline'])
tacred_baseline_mean = tacred_baseline_df.groupby('task_id').mean()
tacred_baseline_mean.T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
avg_precision,0.991896,0.979826,0.975127,0.976641,0.973428,0.966511,0.959227,0.962114
avg_recall,0.991781,0.982115,0.973570,0.975837,0.973332,0.966979,0.960637,0.963467
avg_f1,0.991761,0.980636,0.973735,0.975625,0.972746,0.966054,0.959068,0.962010