In [1]:

import pandas as pd
import json
path = "/Users/sefika/phd_projects/llm-catastrophic-re/results_all/results_rationale_nli/gemini/tacred_mas_top_prob_5/llm_judged_results.json"

In [34]:
def read_json(file_path):
    with open(file_path, "r") as f:
        return json.load(f)

def analyze_tacred_mas(data):
    results = []
    for item in data:
        scores = []
        for record in item['human_judged']:
            try:
                score = record['score'].split('/')[0].split('.')[0]  # Extract the score (e.g., "entailment", "neutral", "contradiction")
                # print(score)
                scores.append(int(score))
            except Exception as e:
                print(f"Error processing record: {record}, error: {e}")   

        results.append({
            'run_id': item['run_id'],
            'scores': scores,
            'len_scores': len(scores)
        })
    return results

In [35]:
tacred_mas = analyze_tacred_mas(read_json(path))
tacred_mas_df = pd.DataFrame(tacred_mas)
tacred_mas_df

Error processing record: {'suggestion': '4. Neutral', 'score': 'way.', 'human_judged': True}, error: invalid literal for int() with base 10: 'way'
Error processing record: {'suggestion': '4. Neutral', 'score': 'confidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'confidence'
Error processing record: {'suggestion': '4. Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. Entailment', 'score': 'residence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'residence'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'these.', 'human_judged': True}, error: invalid literal for int() with base 10: 'these'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'type.', 'human_judged': True}, error: invalid literal for int() with base 10: 'type'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'connection.', 'human_judged': True}, error: invalid literal for int() with base 10: 'connection'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment', 'score': 'province.', 'human_judged': True}, error: invalid literal for int() with base 10: 'province'
Error processing record: {'suggestion': '4. Neutral.', 'score': 'title.', 'human_judged': True}, error: invalid literal for int() with base 10: 'title'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'NDRC.', 'human_judged': True}, error: invalid literal for int() with base 10: 'NDRC'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Neutral.', 'score': 'sentence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'sentence'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. **Classify as**: Neutral', 'score': 'meeting.', 'human_judged': True}, error: invalid literal for int() with base 10: 'meeting'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'organization.', 'human_judged': True}, error: invalid literal for int() with base 10: 'organization'
Error processing record: {'suggestion': 'Neutral.', 'score': 'elsewhere.', 'human_judged': True}, error: invalid literal for int() with base 10: 'elsewhere'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'uncertainty.', 'human_judged': True}, error: invalid literal for int() with base 10: 'uncertainty'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'type.', 'human_judged': True}, error: invalid literal for int() with base 10: 'type'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'confidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'confidence'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. **Classify as**: Entailment', 'score': 'association.', 'human_judged': True}, error: invalid literal for int() with base 10: 'association'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'statement.', 'human_judged': True}, error: invalid literal for int() with base 10: 'statement'
Error processing record: {'suggestion': '4. Neutral.', 'score': 'inference.', 'human_judged': True}, error: invalid literal for int() with base 10: 'inference'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment', 'score': 'text.', 'human_judged': True}, error: invalid literal for int() with base 10: 'text'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Neutral', 'score': 'inference.', 'human_judged': True}, error: invalid literal for int() with base 10: 'inference'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': '`per:charges`.', 'human_judged': True}, error: invalid literal for int() with base 10: '`per:charges`'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'supported.', 'human_judged': True}, error: invalid literal for int() with base 10: 'supported'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Neutral', 'score': 'uncertainty.', 'human_judged': True}, error: invalid literal for int() with base 10: 'uncertainty'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. **Classify as:** Neutral', 'score': 'supported.', 'human_judged': True}, error: invalid literal for int() with base 10: 'supported'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'TPI.', 'human_judged': True}, error: invalid literal for int() with base 10: 'TPI'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'statement.', 'human_judged': True}, error: invalid literal for int() with base 10: 'statement'
Error processing record: {'suggestion': '4. Entailment', 'score': 'type.', 'human_judged': True}, error: invalid literal for int() with base 10: 'type'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'siblings.', 'human_judged': True}, error: invalid literal for int() with base 10: 'siblings'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'membership.', 'human_judged': True}, error: invalid literal for int() with base 10: 'membership'
Error processing record: {'suggestion': 'Classify as: Entailment', 'score': 'certainty.', 'human_judged': True}, error: invalid literal for int() with base 10: 'certainty'
Error processing record: {'suggestion': '4. Entailment', 'score': 'conclusion.', 'human_judged': True}, error: invalid literal for int() with base 10: 'conclusion'
Error processing record: {'suggestion': 'Classify as: Entailment', 'score': 'type.', 'human_judged': True}, error: invalid literal for int() with base 10: 'type'
Error processing record: {'suggestion': '4. Neutral', 'score': 'confident.', 'human_judged': True}, error: invalid literal for int() with base 10: 'confident'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': 'Classify as: Neutral', 'score': 'parent.', 'human_judged': True}, error: invalid literal for int() with base 10: 'parent'
Error processing record: {'suggestion': '4. Entailment', 'score': 'assessment.', 'human_judged': True}, error: invalid literal for int() with base 10: 'assessment'
Error processing record: {'suggestion': 'Neutral.', 'score': 'applicable.', 'human_judged': True}, error: invalid literal for int() with base 10: 'applicable'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Neutral.', 'score': 'parent.', 'human_judged': True}, error: invalid literal for int() with base 10: 'parent'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'doubt.', 'human_judged': True}, error: invalid literal for int() with base 10: 'doubt'
Error processing record: {'suggestion': '4. Entailment', 'score': 'capacities.', 'human_judged': True}, error: invalid literal for int() with base 10: 'capacities'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment.', 'score': 'residence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'residence'
Error processing record: {'suggestion': '4. Entailment.', 'score': 'context.', 'human_judged': True}, error: invalid literal for int() with base 10: 'context'
Error processing record: {'suggestion': '3. **Suggestions:** Human review is recommended to confirm the exact relationship between Vagni and ICRC. While "colleagues" suggests a professional connection, it doesn\'t definitively prove employment.', 'score': 'stated.', 'human_judged': True}, error: invalid literal for int() with base 10: 'stated'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment', 'score': 'this.', 'human_judged': True}, error: invalid literal for int() with base 10: 'this'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'circumstantial.', 'human_judged': True}, error: invalid literal for int() with base 10: 'circumstantial'
Error processing record: {'suggestion': '4. Entailment.', 'score': 'support.', 'human_judged': True}, error: invalid literal for int() with base 10: 'support'
Error processing record: {'suggestion': '4. Entailment', 'score': 'relationship.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relationship'
Error processing record: {'suggestion': '4. **Classify as**: Entailment', 'score': 'probable.', 'human_judged': True}, error: invalid literal for int() with base 10: 'probable'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': '"Potomac".', 'human_judged': True}, error: invalid literal for int() with base 10: '"Potomac"'
Error processing record: {'suggestion': '4. Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. **Classify as:** Neutral', 'score': 'association.', 'human_judged': True}, error: invalid literal for int() with base 10: 'association'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'connection.', 'human_judged': True}, error: invalid literal for int() with base 10: 'connection'
Error processing record: {'suggestion': '4. Entailment', 'score': 'text.', 'human_judged': True}, error: invalid literal for int() with base 10: 'text'
Error processing record: {'suggestion': '4. Neutral', 'score': 'interpretations.', 'human_judged': True}, error: invalid literal for int() with base 10: 'interpretations'
Error processing record: {'suggestion': '4. **Classify as:** Neutral', 'score': 'type.', 'human_judged': True}, error: invalid literal for int() with base 10: 'type'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'high.', 'human_judged': True}, error: invalid literal for int() with base 10: 'high'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. Neutral.', 'score': 'position.', 'human_judged': True}, error: invalid literal for int() with base 10: 'position'
Error processing record: {'suggestion': '4. Entailment', 'score': 'type.', 'human_judged': True}, error: invalid literal for int() with base 10: 'type'
Error processing record: {'suggestion': '4. Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. Entailment', 'score': 'Cross.', 'human_judged': True}, error: invalid literal for int() with base 10: 'Cross'
Error processing record: {'suggestion': 'Neutral.', 'score': 'death.', 'human_judged': True}, error: invalid literal for int() with base 10: 'death'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'origin.', 'human_judged': True}, error: invalid literal for int() with base 10: 'origin'
Error processing record: {'suggestion': '4. Entailment', 'score': 'employment.', 'human_judged': True}, error: invalid literal for int() with base 10: 'employment'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Neutral', 'score': 'ambiguity.', 'human_judged': True}, error: invalid literal for int() with base 10: 'ambiguity'
Error processing record: {'suggestion': 'Entailment', 'score': 'possible.', 'human_judged': True}, error: invalid literal for int() with base 10: 'possible'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Neutral.', 'score': 'residence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'residence'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. **Classify as**: Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'unlikely.', 'human_judged': True}, error: invalid literal for int() with base 10: 'unlikely'
Error processing record: {'suggestion': 'Classify as: Entailment', 'score': 'organization.', 'human_judged': True}, error: invalid literal for int() with base 10: 'organization'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'type.', 'human_judged': True}, error: invalid literal for int() with base 10: 'type'
Error processing record: {'suggestion': '4. Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'relationship.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relationship'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'implication.', 'human_judged': True}, error: invalid literal for int() with base 10: 'implication'
Error processing record: {'suggestion': '4. Classify as : Entailment', 'score': 'text.', 'human_judged': True}, error: invalid literal for int() with base 10: 'text'
Error processing record: {'suggestion': '4. **Classify as**: Entailment', 'score': 'relationship.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relationship'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'acquisition.', 'human_judged': True}, error: invalid literal for int() with base 10: 'acquisition'
Error processing record: {'suggestion': '4. Classify as: Entailment.', 'score': 'org:subsidiaries.', 'human_judged': True}, error: invalid literal for int() with base 10: 'org:subsidiaries'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'pattern.', 'human_judged': True}, error: invalid literal for int() with base 10: 'pattern'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''

   run_id                                             scores  len_scores
0       1  [9, 3, 10, 7, 9, 9, 10, 9, 6, 10, 9, 7, 7, 8, ...        3202
1       2  [3, 9, 9, 9, 8, 10, 8, 10, 2, 10, 8, 9, 8, 9, ...        3197
2       3  [8, 9, 6, 7, 2, 9, 7, 9, 7, 6, 9, 10, 9, 4, 9,...        3208
3       4  [8, 2, 9, 7, 8, 2, 9, 9, 9, 7, 10, 9, 8, 7, 8,...        3202
4       5  [9, 10, 8, 9, 9, 3, 8, 2, 2, 10, 3, 3, 3, 8, 8...        3215

In [36]:
fewrel_path = "/Users/sefika/phd_projects/llm-catastrophic-re/results_all/results_rationale_nli/gemini/fewrel_mas_top_prob_5/llm_judged_results.json"

fewrel = analyze_tacred_mas(read_json(fewrel_path))
fewrel_df = pd.DataFrame(fewrel)
fewrel_df

Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'supported.', 'human_judged': True}, error: invalid literal for int() with base 10: 'supported'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'connection.', 'human_judged': True}, error: invalid literal for int() with base 10: 'connection'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment', 'score': 'text.', 'human_judged': True}, error: invalid literal for int() with base 10: 'text'
Error processing record: {'suggestion': '4. Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. **Classify as:** Neutral', 'score': 'relationship.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relationship'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'inference.', 'human_judged': True}, error: invalid literal for int() with base 10: 'inference'
Error processing record: {'suggestion': 'Classify as: Neutral', 'score': 'sense.', 'human_judged': True}, error: invalid literal for int() with base 10: 'sense'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'presence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'presence'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. Entailment', 'score': "'player'.", 'human_judged': True}, error: invalid literal for int() with base 10: "'player'"
Error processing record: {'suggestion': 'Classify as: Neutral', 'score': 'probabilities.', 'human_judged': True}, error: invalid literal for int() with base 10: 'probabilities'
Error processing record: {'suggestion': '4. Neutral', 'score': 'assumption.', 'human_judged': True}, error: invalid literal for int() with base 10: 'assumption'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'based.', 'human_judged': True}, error: invalid literal for int() with base 10: 'based'
Error processing record: {'suggestion': '4. Neutral.', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. Entailment', 'score': 'sentence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'sentence'
Error processing record: {'suggestion': '4. Entailment', 'score': 'band.', 'human_judged': True}, error: invalid literal for int() with base 10: 'band'
Error processing record: {'suggestion': 'Human suggestion needed.', 'score': 'location.', 'human_judged': True}, error: invalid literal for int() with base 10: 'location'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'sentence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'sentence'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment.', 'score': 'connection.', 'human_judged': True}, error: invalid literal for int() with base 10: 'connection'
Error processing record: {'suggestion': '4. **Classify as:** Neutral', 'score': 'link.', 'human_judged': True}, error: invalid literal for int() with base 10: 'link'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'London.', 'human_judged': True}, error: invalid literal for int() with base 10: 'London'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment.', 'score': 'relationship.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relationship'
Error processing record: {'suggestion': '4. Entailment', 'score': 'location.', 'human_judged': True}, error: invalid literal for int() with base 10: 'location'
Error processing record: {'suggestion': '4. Entailment', 'score': 'hub.', 'human_judged': True}, error: invalid literal for int() with base 10: 'hub'
Error processing record: {'suggestion': '4. Entailment', 'score': 'interpretation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'interpretation'
Error processing record: {'suggestion': '4. **Classify as**: Entailment', 'score': 'connection.', 'human_judged': True}, error: invalid literal for int() with base 10: 'connection'
Error processing record: {'suggestion': '4. **Classify as**: Entailment', 'score': 'text.', 'human_judged': True}, error: invalid literal for int() with base 10: 'text'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'residence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'residence'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'strong.', 'human_judged': True}, error: invalid literal for int() with base 10: 'strong'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '3. Suggestions: Human suggestion needed.', 'score': 'dwelling.', 'human_judged': True}, error: invalid literal for int() with base 10: 'dwelling'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4, Neutral', 'score': 'it.', 'human_judged': True}, error: invalid literal for int() with base 10: 'it'
Error processing record: {'suggestion': '4. Classify as : Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. Neutral', 'score': 'entities.', 'human_judged': True}, error: invalid literal for int() with base 10: 'entities'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment', 'score': 'entities.', 'human_judged': True}, error: invalid literal for int() with base 10: 'entities'
Error processing record: {'suggestion': '4. Entailment.', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4, Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. **Classify as:** Neutral', 'score': 'one.', 'human_judged': True}, error: invalid literal for int() with base 10: 'one'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4, Entailment', 'score': 'likelihood.', 'human_judged': True}, error: invalid literal for int() with base 10: 'likelihood'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment', 'score': 'confident.', 'human_judged': True}, error: invalid literal for int() with base 10: 'confident'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. Neutral', 'score': 'itself.', 'human_judged': True}, error: invalid literal for int() with base 10: 'itself'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'architect.', 'human_judged': True}, error: invalid literal for int() with base 10: 'architect'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment', 'score': 'Center.', 'human_judged': True}, error: invalid literal for int() with base 10: 'Center'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'connection.', 'human_judged': True}, error: invalid literal for int() with base 10: 'connection'
Error processing record: {'suggestion': '4. Entailment', 'score': 'connection.', 'human_judged': True}, error: invalid literal for int() with base 10: 'connection'
Error processing record: {'suggestion': '4. Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'action.', 'human_judged': True}, error: invalid literal for int() with base 10: 'action'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Neutral', 'score': '"has_part".', 'human_judged': True}, error: invalid literal for int() with base 10: '"has_part"'
Error processing record: {'suggestion': 'Neutral.', 'score': 'Music.', 'human_judged': True}, error: invalid literal for int() with base 10: 'Music'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Neutral', 'score': 'uncertainty.', 'human_judged': True}, error: invalid literal for int() with base 10: 'uncertainty'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'interpretation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'interpretation'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'this.', 'human_judged': True}, error: invalid literal for int() with base 10: 'this'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'acquisition.', 'human_judged': True}, error: invalid literal for int() with base 10: 'acquisition'
Error processing record: {'suggestion': '4. Entailment', 'score': 'types.', 'human_judged': True}, error: invalid literal for int() with base 10: 'types'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'entity.', 'human_judged': True}, error: invalid literal for int() with base 10: 'entity'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'type.', 'human_judged': True}, error: invalid literal for int() with base 10: 'type'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Entailment', 'score': 'it.', 'human_judged': True}, error: invalid literal for int() with base 10: 'it'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'sentence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'sentence'
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'low.', 'human_judged': True}, error: invalid literal for int() with base 10: 'low'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'cue.', 'human_judged': True}, error: invalid literal for int() with base 10: 'cue'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '**2. Explanation:** The sentence states that "gekiga artwork by Saitō Takao". This direct attribution strongly suggests that Saitō Takao is associated with the creation or defining of "gekiga" as a style or genre. While "artwork by" is not explicitly "genre", in the context of artistic creation, it often implies that the artist is a prominent figure within or a creator of that genre. The probability score of 4.766905 for "genre" from the provided list is the highest, further supporting this interpretation.', 'score': 'rationale:', 'human_judged': True}, error: invalid literal for int() with base 10: 'rationale:'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'interpretations.', 'human_judged': True}, error: invalid literal for int() with base 10: 'interpretations'
Error processing record: {'suggestion': '4. Entailment', 'score': 'game.', 'human_judged': True}, error: invalid literal for int() with base 10: 'game'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'fit.', 'human_judged': True}, error: invalid literal for int() with base 10: 'fit'
Error processing record: {'suggestion': '4. **Classify as:** Entailment', 'score': 'text.', 'human_judged': True}, error: invalid literal for int() with base 10: 'text'
Error processing record: {'suggestion': '4. Entailment', 'score': 'implied.', 'human_judged': True}, error: invalid literal for int() with base 10: 'implied'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'Majorca.', 'human_judged': True}, error: invalid literal for int() with base 10: 'Majorca'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'spouses.', 'human_judged': True}, error: invalid literal for int() with base 10: 'spouses'
Error processing record: {'suggestion': '4. Classify as : Entailment', 'score': 'evidence.', 'human_judged': True}, error: invalid literal for int() with base 10: 'evidence'
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'spouses.', 'human_judged': True}, error: invalid literal for int() with base 10: 'spouses'
Error processing record: {'suggestion': '4. Neutral.', 'score': 'alone.', 'human_judged': True}, error: invalid literal for int() with base 10: 'alone'
Error processing record: {'suggestion': '4. Entailment', 'score': 'probable.', 'human_judged': True}, error: invalid literal for int() with base 10: 'probable'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'relation.', 'human_judged': True}, error: invalid literal for int() with base 10: 'relation'
Error processing record: {'suggestion': '4. Entailment', 'score': 'probable.', 'human_judged': True}, error: invalid literal for int() with base 10: 'probable'
Error processing record: {'suggestion': '4. Neutral', 'score': '"performer_in".', 'human_judged': True}, error: invalid literal for int() with base 10: '"performer_in"'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Neutral', 'score': 'composer.', 'human_judged': True}, error: invalid literal for int() with base 10: 'composer'
Error processing record: {'suggestion': '4. Neutral.', 'score': 'screenplay.', 'human_judged': True}, error: invalid literal for int() with base 10: 'screenplay'
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '', 'score': '', 'human_judged': False}, error: invalid literal for int() with base 10: ''
Error processing record: {'suggestion': '4. Classify as: Entailment', 'score': 'attribution.', 'human_judged': True}, error: invalid literal for int() with base 10: 'attribution'

   run_id                                             scores  len_scores
0       1  [10, 9, 9, 10, 9, 9, 10, 9, 10, 8, 9, 8, 9, 9,...       10640
1       2  [10, 7, 8, 2, 10, 10, 10, 9, 8, 9, 10, 8, 8, 1...       10731
2       3  [9, 9, 7, 9, 9, 3, 2, 7, 7, 8, 8, 7, 9, 7, 8, ...       10659
3       4  [8, 8, 7, 6, 3, 2, 8, 7, 7, 9, 2, 10, 3, 2, 7,...       10740
4       5  [7, 3, 6, 8, 6, 7, 7, 3, 3, 3, 3, 2, 2, 8, 2, ...       10646