In [2]:
import pandas as pd

In [3]:
validation_files={
    'ewc':"/Users/sefika/phd_projects/llm-catastrophic-re/results_all/fewrel_corrected_results/tmlr/ewc/canonical_errors/validation_results.json",
    'mas':"/Users/sefika/phd_projects/llm-catastrophic-re/results_all/fewrel_corrected_results/tmlr/mas/canonical_errors/validation_results.json",
    'baseline':"/Users/sefika/phd_projects/llm-catastrophic-re/results_all/fewrel_corrected_results/tmlr/baseline/canonical_errors/validation_results.json",
    'si':"/Users/sefika/phd_projects/llm-catastrophic-re/results_all/fewrel_corrected_results/tmlr/si/canonical_errors/validation_results.json"   
}

In [1]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [23]:
def inverse_analysis(df_ewc, message_type='Inverse'):
    results = []

    for run_id in range(1,6):

        for task_id in range(1,9):
            count = 0
            no_match =0

            task_relations = df_ewc[(df_ewc['run_id']==run_id) & (df_ewc['task_id']==task_id)]
            task_preds_soft = []
            gt_relations = []
            for inverse_index, inverse_row in task_relations.iterrows():
                gt_relation = inverse_row['gt_relation']
                suggestions = inverse_row['suggestions']
                
                if suggestions!="None":
                    candidates = suggestions + [inverse_row['prediction']]
                else:
                    candidates = [inverse_row['prediction']]
                if gt_relation in candidates:
                    task_preds_soft.append(gt_relation)
                else:
                    task_preds_soft.append(inverse_row['prediction'])

                gt_relations.append(gt_relation)
            acc = accuracy_score(gt_relations, task_preds_soft)
            # print(f"Run ID: {run_id}, Task ID: {task_id}, {message_type} Accuracy: {acc}")
            results.append({
                'run_id': run_id,
                'task_id': task_id,
                'accuracy': acc
            })
            
            
    return results

In [25]:
df_pred = pd.json_normalize(pd.read_json(validation_files['baseline']).to_dict(orient="records"))
results = inverse_analysis(df_pred, message_type='Canonical')
results_df = pd.DataFrame(results)
results_df.groupby('task_id').mean().T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
accuracy,0.977571,0.909143,0.878333,0.869857,0.859143,0.865571,0.866082,0.860625

In [26]:
df_pred = pd.json_normalize(pd.read_json(validation_files['ewc']).to_dict(orient="records"))
results = inverse_analysis(df_pred, message_type='Canonical')
results_df = pd.DataFrame(results)
results_df.groupby('task_id').mean().T

task_id,1,2,3,4,5,6,7,8
run_id,3.000,3.000000,3.000000,3.00000,3.000000,3.000000,3.000000,3.000000
accuracy,0.981,0.907571,0.872476,0.86825,0.859057,0.858262,0.855306,0.856625

In [27]:
df_pred = pd.json_normalize(pd.read_json(validation_files['mas']).to_dict(orient="records"))
results = inverse_analysis(df_pred, message_type='Canonical')
results_df = pd.DataFrame(results)
results_df.groupby('task_id').mean().T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.00000,3.000000,3.000000,3.000000,3.000000,3.000000
accuracy,0.980571,0.910429,0.87281,0.869643,0.858057,0.856429,0.854878,0.856089

In [28]:
df_pred = pd.json_normalize(pd.read_json(validation_files['si']).to_dict(orient="records"))
results = inverse_analysis(df_pred, message_type='Canonical')
results_df = pd.DataFrame(results)
results_df.groupby('task_id').mean().T

task_id,1,2,3,4,5,6,7,8
run_id,3.000000,3.000000,3.00000,3.000000,3.000000,3.000000,3.000000,3.000000
accuracy,0.977571,0.911429,0.88319,0.873464,0.861857,0.865476,0.864388,0.860768